stages:
  archive-2020-11-16:
    cmd: podman run -v /home/ebodea/src/COVID-stochastic-fitting/local-run:/root -e
      fdt=2020-11-16 -w /root --rm eamon/2020mif:v20201129 ./pull-current-output-from-date.R
    deps:
    - pull-current-output-from-date.R
    outs:
    - archive/2020-11-16
  simulate-2020-11-16:
    cmd: podman run -v /home/ebodea/src/COVID-stochastic-fitting/local-run/..:/root
      -e fdt=2020-11-16 -w /root/local-run --rm eamon/2020mif:v20201129 bash -x ./run-simulations.sh
    deps:
    - ../code
    - ../data/us_popsize.rds
    - archive/2020-11-16
    - run-simulations.sh
    - weekly-forecast.R
    outs:
    - weekly-forecast-simulations/2020-11-16
  format-2020-11-16:
    cmd: podman run -v /home/ebodea/src/COVID-stochastic-fitting/local-run:/root -e
      fdt=2020-11-16 -w /root --rm eamon/2020mif:v20201129 ./format-simulations.R
    deps:
    - format-simulations.R
    - weekly-forecast-simulations/2020-11-16
    outs:
    - CEID-compart_mif_li/2020-11-16-CEID-compart_mif_li.csv
    - CEID-compart_mif_rn/2020-11-16-CEID-compart_mif_rn.csv
    - CEID-compart_mif_sq/2020-11-16-CEID-compart_mif_sq.csv
  archive-2020-11-09:
    cmd: podman run -v /home/ebodea/src/COVID-stochastic-fitting/local-run:/root -e
      fdt=2020-11-09 -w /root --rm eamon/2020mif:v20201129 ./pull-current-output-from-date.R
    deps:
    - pull-current-output-from-date.R
    outs:
    - archive/2020-11-09
  simulate-2020-11-09:
    cmd: podman run -v /home/ebodea/src/COVID-stochastic-fitting/local-run/..:/root
      -e fdt=2020-11-09 -w /root/local-run --rm eamon/2020mif:v20201129 bash -x ./run-simulations.sh
    deps:
    - ../code
    - ../data/us_popsize.rds
    - archive/2020-11-09
    - run-simulations.sh
    - weekly-forecast.R
    outs:
    - weekly-forecast-simulations/2020-11-09
  format-2020-11-09:
    cmd: podman run -v /home/ebodea/src/COVID-stochastic-fitting/local-run:/root -e
      fdt=2020-11-09 -w /root --rm eamon/2020mif:v20201129 ./format-simulations.R
    deps:
    - format-simulations.R
    - weekly-forecast-simulations/2020-11-09
    outs:
    - CEID-compart_mif_li/2020-11-09-CEID-compart_mif_li.csv
    - CEID-compart_mif_rn/2020-11-09-CEID-compart_mif_rn.csv
    - CEID-compart_mif_sq/2020-11-09-CEID-compart_mif_sq.csv
  archive-2020-11-02:
    cmd: podman run -v /home/ebodea/src/COVID-stochastic-fitting/local-run:/root -e
      fdt=2020-11-02 -w /root --rm eamon/2020mif:v20201129 ./pull-current-output-from-date.R
    deps:
    - pull-current-output-from-date.R
    outs:
    - archive/2020-11-02
  simulate-2020-11-02:
    cmd: podman run -v /home/ebodea/src/COVID-stochastic-fitting/local-run/..:/root
      -e fdt=2020-11-02 -w /root/local-run --rm eamon/2020mif:v20201129 bash -x ./run-simulations.sh
    deps:
    - ../code
    - ../data/us_popsize.rds
    - archive/2020-11-02
    - run-simulations.sh
    - weekly-forecast.R
    outs:
    - weekly-forecast-simulations/2020-11-02
  format-2020-11-02:
    cmd: podman run -v /home/ebodea/src/COVID-stochastic-fitting/local-run:/root -e
      fdt=2020-11-02 -w /root --rm eamon/2020mif:v20201129 ./format-simulations.R
    deps:
    - format-simulations.R
    - weekly-forecast-simulations/2020-11-02
    outs:
    - CEID-compart_mif_li/2020-11-02-CEID-compart_mif_li.csv
    - CEID-compart_mif_rn/2020-11-02-CEID-compart_mif_rn.csv
    - CEID-compart_mif_sq/2020-11-02-CEID-compart_mif_sq.csv
  archive-2020-10-26:
    cmd: podman run -v /home/ebodea/src/COVID-stochastic-fitting/local-run:/root -e
      fdt=2020-10-26 -w /root --rm eamon/2020mif:v20201129 ./pull-current-output-from-date.R
    deps:
    - pull-current-output-from-date.R
    outs:
    - archive/2020-10-26
  simulate-2020-10-26:
    cmd: podman run -v /home/ebodea/src/COVID-stochastic-fitting/local-run/..:/root
      -e fdt=2020-10-26 -w /root/local-run --rm eamon/2020mif:v20201129 bash -x ./run-simulations.sh
    deps:
    - ../code
    - ../data/us_popsize.rds
    - archive/2020-10-26
    - run-simulations.sh
    - weekly-forecast.R
    outs:
    - weekly-forecast-simulations/2020-10-26
  archive-2020-10-19:
    cmd: podman run -v /home/ebodea/src/COVID-stochastic-fitting/local-run:/root -e
      fdt=2020-10-19 -w /root --rm eamon/2020mif:v20201129 ./pull-current-output-from-date.R
    deps:
    - pull-current-output-from-date.R
    outs:
    - archive/2020-10-19
  simulate-2020-10-19:
    cmd: podman run -v /home/ebodea/src/COVID-stochastic-fitting/local-run/..:/root
      -e fdt=2020-10-19 -w /root/local-run --rm eamon/2020mif:v20201129 bash -x ./run-simulations.sh
    deps:
    - ../code
    - ../data/us_popsize.rds
    - archive/2020-10-19
    - run-simulations.sh
    - weekly-forecast.R
    outs:
    - weekly-forecast-simulations/2020-10-19
  archive-2020-10-12:
    cmd: podman run -v /home/ebodea/src/COVID-stochastic-fitting/local-run:/root -e
      fdt=2020-10-12 -w /root --rm eamon/2020mif:v20201129 ./pull-current-output-from-date.R
    deps:
    - pull-current-output-from-date.R
    outs:
    - archive/2020-10-12
  simulate-2020-10-12:
    cmd: podman run -v /home/ebodea/src/COVID-stochastic-fitting/local-run/..:/root
      -e fdt=2020-10-12 -w /root/local-run --rm eamon/2020mif:v20201129 bash -x ./run-simulations.sh
    deps:
    - ../code
    - ../data/us_popsize.rds
    - archive/2020-10-12
    - run-simulations.sh
    - weekly-forecast.R
    outs:
    - weekly-forecast-simulations/2020-10-12
  archive-2020-10-05:
    cmd: podman run -v /home/ebodea/src/COVID-stochastic-fitting/local-run:/root -e
      fdt=2020-10-05 -w /root --rm eamon/2020mif:v20201129 ./pull-current-output-from-date.R
    deps:
    - pull-current-output-from-date.R
    outs:
    - archive/2020-10-05
  simulate-2020-10-05:
    cmd: podman run -v /home/ebodea/src/COVID-stochastic-fitting/local-run/..:/root
      -e fdt=2020-10-05 -w /root/local-run --rm eamon/2020mif:v20201129 bash -x ./run-simulations.sh
    deps:
    - ../code
    - ../data/us_popsize.rds
    - archive/2020-10-05
    - run-simulations.sh
    - weekly-forecast.R
    outs:
    - weekly-forecast-simulations/2020-10-05
  archive-2020-09-28:
    cmd: podman run -v /home/ebodea/src/COVID-stochastic-fitting/local-run:/root -e
      fdt=2020-09-28 -w /root --rm eamon/2020mif:v20201129 ./pull-current-output-from-date.R
    deps:
    - pull-current-output-from-date.R
    outs:
    - archive/2020-09-28
  simulate-2020-09-28:
    cmd: podman run -v /home/ebodea/src/COVID-stochastic-fitting/local-run/..:/root
      -e fdt=2020-09-28 -w /root/local-run --rm eamon/2020mif:v20201129 bash -x ./run-simulations.sh
    deps:
    - ../code
    - ../data/us_popsize.rds
    - archive/2020-09-28
    - run-simulations.sh
    - weekly-forecast.R
    outs:
    - weekly-forecast-simulations/2020-09-28
  archive-2020-09-21:
    cmd: podman run -v /home/ebodea/src/COVID-stochastic-fitting/local-run:/root -e
      fdt=2020-09-21 -w /root --rm eamon/2020mif:v20201129 ./pull-current-output-from-date.R
    deps:
    - pull-current-output-from-date.R
    outs:
    - archive/2020-09-21
  simulate-2020-09-21:
    cmd: podman run -v /home/ebodea/src/COVID-stochastic-fitting/local-run/..:/root
      -e fdt=2020-09-21 -w /root/local-run --rm eamon/2020mif:v20201129 bash -x ./run-simulations.sh
    deps:
    - ../code
    - ../data/us_popsize.rds
    - archive/2020-09-21
    - run-simulations.sh
    - weekly-forecast.R
    outs:
    - weekly-forecast-simulations/2020-09-21
  archive-2020-09-14:
    cmd: podman run -v /home/ebodea/src/COVID-stochastic-fitting/local-run:/root -e
      fdt=2020-09-14 -w /root --rm eamon/2020mif:v20201129 ./pull-current-output-from-date.R
    deps:
    - pull-current-output-from-date.R
    outs:
    - archive/2020-09-14
  format-2020-10-26:
    cmd: podman run -v /home/ebodea/src/COVID-stochastic-fitting/local-run:/root -e
      fdt=2020-10-26 -w /root --rm eamon/2020mif:v20201129 ./format-simulations.R
    deps:
    - format-simulations.R
    - weekly-forecast-simulations/2020-10-26
    outs:
    - CEID-compart_mif_li/2020-10-26-CEID-compart_mif_li.csv
    - CEID-compart_mif_rn/2020-10-26-CEID-compart_mif_rn.csv
    - CEID-compart_mif_sq/2020-10-26-CEID-compart_mif_sq.csv
  format-2020-10-19:
    cmd: podman run -v /home/ebodea/src/COVID-stochastic-fitting/local-run:/root -e
      fdt=2020-10-19 -w /root --rm eamon/2020mif:v20201129 ./format-simulations.R
    deps:
    - format-simulations.R
    - weekly-forecast-simulations/2020-10-19
    outs:
    - CEID-compart_mif_li/2020-10-19-CEID-compart_mif_li.csv
    - CEID-compart_mif_rn/2020-10-19-CEID-compart_mif_rn.csv
    - CEID-compart_mif_sq/2020-10-19-CEID-compart_mif_sq.csv
  format-2020-10-12:
    cmd: podman run -v /home/ebodea/src/COVID-stochastic-fitting/local-run:/root -e
      fdt=2020-10-12 -w /root --rm eamon/2020mif:v20201129 ./format-simulations.R
    deps:
    - format-simulations.R
    - weekly-forecast-simulations/2020-10-12
    outs:
    - CEID-compart_mif_li/2020-10-12-CEID-compart_mif_li.csv
    - CEID-compart_mif_rn/2020-10-12-CEID-compart_mif_rn.csv
    - CEID-compart_mif_sq/2020-10-12-CEID-compart_mif_sq.csv
  format-2020-10-05:
    cmd: podman run -v /home/ebodea/src/COVID-stochastic-fitting/local-run:/root -e
      fdt=2020-10-05 -w /root --rm eamon/2020mif:v20201129 ./format-simulations.R
    deps:
    - format-simulations.R
    - weekly-forecast-simulations/2020-10-05
    outs:
    - CEID-compart_mif_li/2020-10-05-CEID-compart_mif_li.csv
    - CEID-compart_mif_rn/2020-10-05-CEID-compart_mif_rn.csv
    - CEID-compart_mif_sq/2020-10-05-CEID-compart_mif_sq.csv
  format-2020-09-28:
    cmd: podman run -v /home/ebodea/src/COVID-stochastic-fitting/local-run:/root -e
      fdt=2020-09-28 -w /root --rm eamon/2020mif:v20201129 ./format-simulations.R
    deps:
    - format-simulations.R
    - weekly-forecast-simulations/2020-09-28
    outs:
    - CEID-compart_mif_li/2020-09-28-CEID-compart_mif_li.csv
    - CEID-compart_mif_rn/2020-09-28-CEID-compart_mif_rn.csv
    - CEID-compart_mif_sq/2020-09-28-CEID-compart_mif_sq.csv
  format-2020-09-21:
    cmd: podman run -v /home/ebodea/src/COVID-stochastic-fitting/local-run:/root -e
      fdt=2020-09-21 -w /root --rm eamon/2020mif:v20201129 ./format-simulations.R
    deps:
    - format-simulations.R
    - weekly-forecast-simulations/2020-09-21
    outs:
    - CEID-compart_mif_li/2020-09-21-CEID-compart_mif_li.csv
    - CEID-compart_mif_rn/2020-09-21-CEID-compart_mif_rn.csv
    - CEID-compart_mif_sq/2020-09-21-CEID-compart_mif_sq.csv
  evaluate:
    cmd: 'podman run -v /home/ebodea/src/COVID-stochastic-fitting/local-run:/root
      -w /root --rm eamon/2020mif:v20201129 Rscript -e "knitr::spin(\"evaluate-forecasts.R\")" '
    deps:
    - CEID-compart_mif_li
    - CEID-compart_mif_rn
    - CEID-compart_mif_sq
    - evaluate-forecasts.R
    outs:
    - case-trajectories.png
    - death-trajectories.png
    - evaluate-forecasts.html
